### ISSUE TITLE
MDI_NULL_COMM naming convention?

### ISSUE THREAD

**Issue by zerothi** [MolSSI/MDI_Library#67]
I am trying to read through your MDI work, really nice.

Wouldn't it make sense to follow MPI naming conventions?

You use `MDI_NULL_COMM`, but I think it would be more natural to use `MDI_COMM_NULL`?

**Comment by taylor-a-barnes** [comment]
@zerothi You're certainly correct - thanks for catching this.  Feel free to point out any other inconsistencies.
